services:
  # 1. RabbitMQ (The Message Broker)
  atlas-rabbitmq:
    image: rabbitmq:3-management
    container_name: atlas-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atlas-network

  # 2. PostgreSQL (The Relational DB - Command Service & Booking)
  atlas-postgres:
    image: postgres:15
    container_name: atlas-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - atlas-network

  # 3. MongoDB (The NoSQL DB - Read Models)
  atlas-mongo:
    image: mongo:latest
    container_name: atlas-mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - atlas-network

  # 4. Redis (The Cache)
  atlas-redis:
    image: redis:alpine
    container_name: atlas-redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - atlas-network

  # 5. Command Service (Node.js - Writes)
  command-service:
    build: ./command-service
    volumes:
      - ./docker/postgres/scripts:/docker/postgres/scripts
    container_name: atlas-command-service
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/
    depends_on:
      atlas-rabbitmq:
        condition: service_healthy
      atlas-postgres:
        condition: service_started
    networks:
      - atlas-network

  # 6. Query Service (Go - Reads & Booking Processing)
  query-service:
    build: ./query-service
    container_name: atlas-query-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - GIN_MODE=${GIN_MODE}
      # RabbitMQ
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/
      - RABBITMQ_TICKET_QUEUE=${TICKET_QUEUE}
      # Databases
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - MONGO_URI=mongodb://${MONGO_HOST}:${MONGO_PORT}
      - REDIS_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # App Config
      - DB_NAME=${MONGO_DB_NAME}
      - COLLECTION_NAME=${MONGO_COLLECTION}
    depends_on:
      - atlas-rabbitmq
      - atlas-postgres
      - atlas-mongo
      - atlas-redis
    networks:
      - atlas-network

networks:
  atlas-network:
    driver: bridge
