#We want the command-service to scale up rapidly when the 50,000 users hit the API, while the query-service (Go) can remain more stable due to its high-concurrency worker pool.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: command-service-hpa
  namespace: atlastickets
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: command-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # Scale up if CPU exceeds 60%
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: query-service-hpa
  namespace: atlastickets
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: query-service
  minReplicas: 5
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70