#ConfigMap: Stores configuration data (non-sensitive) that the apps need.

apiVersion: v1
kind: ConfigMap
metadata:
  name: atlastickets-config
  namespace: atlastickets
data:
  #Configuration used by Service
  # PostgreSQL
  POSTGRES_DB: "atlastickets"
  # MongoDB
  MONGO_DB: "tickets"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB_INDEX: "0"

  # RabbitMQ
  RABBITMQ_QUEUE_TICKET: "ticket_queue"

  # Application tuning
  WORKER_POOL_SIZE: "10"