apiVersion: v1
kind: Secret
metadata:
  name: atlastickets-secrets
  namespace: atlastickets
type: Opaque
stringData:
  DB_USER : "atlas"

  DB_PASSWORD : "your_password"

  POSTGRES_URL : "postgres://atlas:your_password@postgres:5432/atlastickets"

  RABBITMQ_URL : "amqp://guest:guest@rabbitmq:5672/"

  MONGO_URI : "mongodb://mongo:27017"

  REDIS_PASSWORD : 