apiVersion: v1
kind: Secret
metadata:
  name: atlastickets-secrets
  namespace: atlastickets
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER: "atlas"
  POSTGRES_PASSWORD: "your_password"
  POSTGRES_URL: "postgres://atlas:your_password@postgres-service:5432/atlastickets"

  # MongoDB
  MONGO_URI: "mongodb://mongo-service:27017"

  # RabbitMQ
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"

  # Redis
  REDIS_PASSWORD: ""